import Image from "next/image";
import ProductListing from "../../Components/ProductListing";


export const metadata = {
  title: "Men Category",
  description: "Generated by create next app",
};

export default function Home() {

  return (
    <>
      <ProductListing/>
    </>
  );
}
