import CartPage from "../Components/CartPage";

export const metadata = {
  title: "Cart - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <CartPage/>
    </>
  );
}
