import Image from "next/image";

export const metadata = {
  title: "Admin Panel",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      Login Page
    </>
  );
}
