import SignUp from "../Components/SignUp";

export const metadata = {
  title: "Sign Up - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <SignUp/>
    </>
  );
}
