import ProductListing from "../Components/ProductListing";

export const metadata = {
  title: "Products - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <ProductListing/>
    </>
  );
}
