import Image from "next/image";
import Commonlayout from "../Commonlayout";

export const metadata = {
  title: "Dashboard | Admin Panel",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <Commonlayout >
      Dashboard Page
    </Commonlayout>
      
    </>
  );
}
