import Home from "./Components/Home";

export const metadata = {
  title: "MayBell - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Home/>
    </>
  );
}
