import ProductDetail from "@/app/Components/ProductDetail";

export const metadata = {
  title: "Product Details - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
        <ProductDetail/>
    </>
  );
}
