import Login from "../Components/Login";

export const metadata = {
  title: "Login - Online furniture store",
  description: "Generated by create next app",
};

export default function page() {
  return (
    <>
      <Login/>
    </>
  );
}
