import Image from "next/image";

export const metadata = {
  title: "Website",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
      Home Page
    </>
  );
}
